# Generated by Django 3.1 on 2023-05-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDeshuezadero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='foto',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appDeshuezadero.cliente'),
        ),
        migrations.CreateModel(
            name='RepuestoFotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='default.png', upload_to='repuestos')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appDeshuezadero.repuesto')),
            ],
            options={
                'verbose_name': 'FotoRepuesto',
                'verbose_name_plural': 'FotosRepuestos',
                'db_table': 'repuesto_foto',
            },
        ),
    ]
