# Generated by Django 3.1 on 2023-05-16 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDeshuezadero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialpago',
            name='valor_neto',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='AutoFotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='/', upload_to='uploads/autos')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appDeshuezadero.auto')),
            ],
            options={
                'verbose_name': 'FotosAutos',
                'verbose_name_plural': 'FotosAutos',
                'db_table': 'auto_foto',
            },
        ),
    ]
