# Generated by Django 3.1 on 2023-05-16 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDeshuezadero', '0002_auto_20230516_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appDeshuezadero.cliente'),
        ),
    ]
