# Generated by Django 3.1 on 2023-05-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeshuezadero', '0002_auto_20230515_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuestofotos',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='static/uploads/repuestos'),
        ),
    ]
