# Generated by Django 3.1 on 2023-05-16 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDeshuezadero', '0003_auto_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='auto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appDeshuezadero.auto'),
        ),
    ]
