# Generated by Django 3.1 on 2023-05-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeshuezadero', '0005_auto_20230516_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='suma',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historialpago',
            name='valor_neto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
