# Generated by Django 3.1 on 2023-05-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDeshuezadero', '0005_auto_20230513_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dv',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='run',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appDeshuezadero.comuna'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appDeshuezadero.genero'),
        ),
    ]
